---
- name: "Operational: Configure Chrony Time Synchronization"
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../../inventory/group_vars/vault_inventory.yml"
  tasks:
    - name: Run Chrony task
      ansible.builtin.include_role:
        name: common
        tasks_from: chrony
