---
- name: "Operational: Install Python Packages"
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Load python package definitions
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../../roles/common/vars/packages/python.yml"

    - name: Install Python packages on standard hosts
      ansible.builtin.apt:
        name: "{{ python_packages }}"
        state: present
      when: node_class | default('vm') != 'proxmox'
