---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: node_class | default('vm') != 'proxmox'

- name: Perform safe upgrade
  ansible.builtin.apt:
    upgrade: safe
  when: node_class | default('vm') != 'proxmox'

